# Generated by Django 2.2.10 on 2023-08-28 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_auto_20230828_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmblDownloadModel',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 19, 11, 27, 114452)),
        ),
    ]
