# Generated by Django 2.2.10 on 2023-08-28 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_auto_20230828_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 21, 18, 35, 925830)),
        ),
        migrations.AlterField(
            model_name='primers',
            name='Query',
            field=models.CharField(max_length=100, verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='primers',
            name='Sequence_Quantity',
            field=models.IntegerField(verbose_name='Sequence_quantity'),
        ),
    ]
