# Generated by Django 2.2.10 on 2023-08-29 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_auto_20230828_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 19, 57, 6, 638710)),
        ),
        migrations.AlterField(
            model_name='primers',
            name='Sequence_Quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Sequence_quantity'),
        ),
    ]
