# Generated by Django 2.2.10 on 2024-01-03 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0036_auto_20230829_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 15, 34, 18, 919521)),
        ),
    ]
